services:
  - type: web
    name: moon-gallery-pos-web
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
